#!/usr/bin/env python
# coding: utf-8

myDoc = [
    {
        "full_text": "hello",
        "spans": [
            {
                "entity_type": "ORG",
                "entity_value": "Republic of Turkey",
                "start_position": 76,
                "end_position": 94
            },
            {
                "entity_type": "DEM",
                "entity_value": "Turkish",
                "start_position": 236,
                "end_position": 243
            },
            {
                "entity_type": "PERSON",
                "entity_value": "Mr Cengiz Polat",
                "start_position": 254,
                "end_position": 269
            }
        ]
    },
    {
        "full_text": "hello",
        "spans": [
            {
                "entity_type": "ORG",
                "entity_value": "Republic of Turkey",
                "start_position": 76,
                "end_position": 94
            },
            {
                "entity_type": "DEM",
                "entity_value": "Turkish",
                "start_position": 236,
                "end_position": 243
            },
            {
                "entity_type": "PERSON",
                "entity_value": "Mr Cengiz Polat",
                "start_position": 254,
                "end_position": 269
            }
        ]
    }
    ]
def de_dupe(duplicated_list:list):
    deduplicated_list = list()
    for item in duplicated_list:
        if item not in deduplicated_list:
            deduplicated_list.append(item)
    return deduplicated_list

#myList = list(set(myList))
print(len(myDoc))
r = de_dupe(myDoc)
print(len(r))

# before fine-tuning with 'en_core_web_md'
# baseline
[('SIDDHARTH RAGHUVANSHI Roll', 'PERSON'),
('Mobile', 'GPE'),
('Computer Science & Engineering', 'ORG'),
('Institute/ School', 'ORG'),
('Kharagpur\nCentral Hindu School', 'ORG'),
('Varanasi', 'GPE'),
('Varanasi', 'GPE'),
('8.26/10', 'CARDINAL'),
('86.0%', 'PERCENT'),
('90.8%', 'PERCENT'),
('2011\n2005', 'DATE'),
('2003', 'DATE'),
('116', 'CARDINAL'),
('AIEEE', 'GPE'),
('2006', 'DATE'),
('470,000', 'CARDINAL'),
('State', 'ORG'),
('8', 'CARDINAL'),
('Uttar Pradesh', 'GPE'),
('119', 'CARDINAL'),
('7th', 'ORDINAL'),
('National Science Olympiad, 2005', 'EVENT'),
('22', 'CARDINAL'),
('Central Institute', 'ORG'),
('English', 'LANGUAGE'),
('CIPEL', 'PERSON'),
('1%', 'PERCENT'),
('26968', 'CARDINAL'),
('National Standard Examination', 'ORG'),
('the past 4 years', 'DATE'),
('M. Tech Project', 'ORG'),
('IIT Kharagpur', 'GPE'),
('May’10', 'GPE'),
('Hadoop', 'ORG'),
('B. Tech Project', 'ORG'),
('IIT Kharagpur', 'GPE'),
('May’10', 'PERSON'),
('IIT Kharagpur May’08', 'ORG'),
('Byte Code Engineering Library', 'ORG'),
('INTERNSHIP\nExtreme Blue Internship Program', 'ORG'),
('ISL', 'ORG'),
('IBM', 'ORG'),
('Pune', 'GPE'),
('India', 'GPE'),
('Pune', 'GPE'),
('kirana', 'GPE'),
('Home Delivery', 'ORG'),
('Java EE', 'ORG'),
('XML', 'ORG'),
('IBM WebSphere Commerce', 'ORG'),
('10/10', 'CARDINAL'),
('summer', 'DATE'),
('IIT Kharagpur', 'ORG'),
('2009', 'DATE'),
('IIT Kharagpur Student Counselling Service', 'ORG'),
('Counselling Centre', 'ORG'),
('IIT Kharagpur', 'GPE'),
('5', 'CARDINAL'),
('a span of 6 months', 'DATE'),
('Feb’09', 'PERSON'),
('Jul’09', 'PERSON'),
('More than 100', 'CARDINAL'),
('every month', 'DATE'),
('Sep’10', 'PERSON'),
('Bitwise-2010', 'PERSON'),
('3000', 'CARDINAL'),
('75', 'CARDINAL'),
('Spring Fest', 'EVENT'),
('2008', 'DATE'),
('inter hall OPENSOFT Competition', 'ORG'),
('2007-08', 'DATE'),
('National Sports Organization', 'ORG'),
('30', 'CARDINAL'),
('Lawn Tennis Team', 'ORG'),
('IIT Kharagpur’06', 'ORG')]

# after fine-tuning md with annotated dataset
[('Institute/ School', 'ORG'),
('Indian Institute of Technology', 'ORG'),
('Kharagpur\nCentral Hindu School', 'ORG'),
('Varanasi', 'GPE'),
('2006', 'DATE'),
('Uttar Pradesh', 'GPE'),
('7th National Science Olympiad', 'ORG'),
('2005', 'DATE'),
('Central Institute  ', 'ORG'),
('English', 'DEM'),
('4 years', 'DATE'),
('IIT Kharagpur May’10-Nov’10', 'ORG'),
('IBM', 'ORG'),
('Pune', 'GPE'),
('India', 'GPE'),
('Pune', 'GPE'),
('Java EE', 'ORG'),
('IBM WebSphere Commerce', 'ORG'),
('IIT Kharagpur', 'ORG'),
('2009', 'DATE'),
('IIT Kharagpur Student Counselling Service', 'ORG'),
('IIT Kharagpur', 'GPE'),
('6 months', 'DATE'),
('Gate Keepers Training', 'ORG'),
('Spring Fest', 'DATE'),
('2008', 'DATE'),
('OPENSOFT Competition', 'ORG'),
('Lawn Tennis Team', 'ORG'),
('IIT', 'GPE')]

# after 2nd step:

2
[('SIDDHARTH RAGHUVANSHI', 'PERSON'),
('08/08/1988', 'ZIP_CODE'),
('siddharth.iitkharagpur@gmail.com', 'EMAIL_ADDRESS'),
('+91 9932584135', 'PHONE_NUMBER'),
('Degree/Certificate', 'ORG'),
('Dual Degree[B. Tech (H) + M. Tech', 'ORG'),
('(Computer Science & Engineering)', 'ORG'),
('Class XII', 'STREET_ADDRESS'),
('C.B.S.E.', 'PHONE_NUMBER'),
('ACADEMIC ACHIEVEMENTS\nInstitute/ School', 'STREET_ADDRESS'),
('City', 'GPE'),
('Indian Institute of Technology', 'ORG'),
('Kharagpur', 'GPE'),
('Central Hindu School', 'ORG'),
('Varanasi', 'GPE'),
('Atulanand Convent School', 'ORG'),
('Varanasi', 'GPE'),
('CGPA/ %', 'ORG'),
('Completion', 'TITLE'),
('8.26/10', 'DATE'),
('86.0%', 'PHONE_NUMBER'),
('90.8%', 'PHONE_NUMBER'),
('2011', 'DATE'),
('2005', 'DATE'),
('2003', 'DATE'),
('Competitive', 'ORG'),
('Examinations', 'TITLE'),
('All India Rank 116', 'STREET_ADDRESS'),
('AIEEE', 'GPE'),
('2006', 'DATE'),
('470,000 students, State Rank 8', 'ORG'),
('Uttar Pradesh', 'GPE'),
('All India Rank 119', 'STREET_ADDRESS'),
('7th National Science Olympiad', 'ORG'),
('2005', 'DATE'),
('All India Rank 22', 'STREET_ADDRESS'),
('All India Level Mathematics & Science Test', 'ORG'),
('Central Institute', 'ORG'),
('Scholastic', 'TITLE'),
('Achievements', 'TITLE'),
('26968', 'PHONE_NUMBER'),
('National Standard Examination', 'ORG'),
('Physics’05', 'GPE'),
('M. Tech Project', 'ORG'),
('IIT Kharagpur', 'ORG'),
('May’10-Nov’10', 'GPE'),
('Hadoop', 'PERSON'),
('B. Tech Project', 'ORG'),
('IIT Kharagpur', 'ORG'),
('Aug’09-May’10', 'GPE'),
('Static Instrumentation Of Java Programs', 'ORG'),
('IIT Kharagpur', 'GPE'),
('May’08', 'TITLE'),
('Byte Code Engineering Library', 'ORG'),
('WORK EXPERIENCE / INTERNSHIP', 'ORG'),
('Extreme Blue Internship Program', 'ORG'),
('ISL', 'GPE'),
('IBM', 'ORG'),
('Pune', 'PERSON'),
('India', 'GPE'),
('May’09', 'GPE'),
('July’09', 'TITLE'),
('Business', 'TITLE'),
('Technical', 'TITLE'),
('Achievements', 'TITLE'),
('Pune', 'GPE'),
('Web Services', 'ORG'),
('Integrated the Home Delivery module', 'ORG'),
('IIT Kharagpur', 'ORG'),
('2009', 'DATE'),
('Distributed Systems', 'ORG'),
('Student coordinator', 'STREET_ADDRESS'),
('IIT Kharagpur Student Counselling Service.', 'ORG'),
('Student', 'TITLE'),
('Counselling Centre', 'ORG'),
('IIT Kharagpur', 'GPE'),
('6 months', 'PHONE_NUMBER'),
('Feb’09 and Jul’09.', 'STREET_ADDRESS'),
('Went through', 'STREET_ADDRESS'),
('Gate Keepers Training', 'ORG'),
('Managed', 'TITLE'),
('Bitwise-2010', 'EMAIL_ADDRESS'),
('3000 teams across 75 countries', 'PHONE_NUMBER'),
('Spring Fest', 'GPE'),
('2008', 'DATE'),
('Senior Secondary School (Central Hindu School', 'ORG'),
('EXTRA CURRICULAR ACHIEVEMENTS', 'ORG'),
('Silver', 'PERSON'),
('OPENSOFT Competition', 'ORG'),
('2007-08.', 'DATE'),
('National Sports Organization', 'ORG'), ('Lawn Tennis Team', 'ORG'),
('IIT Kharagpur’06', 'ORG')
]
